// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const authenticateAPIKey = `-- name: AuthenticateAPIKey :one
UPDATE api_keys
SET last_used_at = now()
WHERE token_hash = $1
  AND (expires_at IS NULL OR expires_at > now())
RETURNING user_id
`

// Resolve a presented token (by its SHA-256 hash) to the owning user id, enforcing
// expiry and touching last_used_at in one atomic statement. No row means the key is
// unknown, revoked, or expired; the caller treats pgx.ErrNoRows as 401.
func (q *Queries) AuthenticateAPIKey(ctx context.Context, tokenHash string) (int64, error) {
	row := q.db.QueryRow(ctx, authenticateAPIKey, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (user_id, name, token_hash, token_prefix, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, token_prefix, created_at, last_used_at, expires_at
`

type CreateAPIKeyParams struct {
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type CreateAPIKeyRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	TokenPrefix string             `json:"token_prefix"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Create an API key for a user. The caller passes the SHA-256 token_hash and the
// display token_prefix; the plaintext token is shown once and never stored.
// expires_at NULL means the key never expires. Returns display fields only, never
// the hash.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenPrefix,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :execrows
DELETE FROM api_keys
WHERE id = $1 AND user_id = $2
`

type DeleteAPIKeyParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"user_id"`
}

// Revoke (delete) a key, scoped to its owner so a user can only delete their own.
// Returns the affected row count: 0 means the key does not exist or is not the
// caller's (the handler maps that to 404).
func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAPIKeysByUser = `-- name: ListAPIKeysByUser :many
SELECT id, name, token_prefix, created_at, last_used_at, expires_at
FROM api_keys
WHERE user_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByUserRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	TokenPrefix string             `json:"token_prefix"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// A user's API keys, newest first. Metadata only — never the token_hash.
func (q *Queries) ListAPIKeysByUser(ctx context.Context, userID int64) ([]ListAPIKeysByUserRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByUserRow{}
	for rows.Next() {
		var i ListAPIKeysByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenPrefix,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
