// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: enrichment.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimEnrichmentBatch = `-- name: ClaimEnrichmentBatch :many
WITH claimable AS (
    SELECT id
    FROM enrichment_outbox
    WHERE failed_at IS NULL
      AND (claimed_at IS NULL
           OR claimed_at < now() - make_interval(secs => $1::int))
    ORDER BY id
    FOR UPDATE SKIP LOCKED
    LIMIT $2
)
UPDATE enrichment_outbox o
SET claimed_at = now()
FROM claimable c
WHERE o.id = c.id
RETURNING o.id, o.job_id, o.target_version
`

type ClaimEnrichmentBatchParams struct {
	LeaseSeconds int32 `json:"lease_seconds"`
	BatchSize    int32 `json:"batch_size"`
}

type ClaimEnrichmentBatchRow struct {
	ID            int64 `json:"id"`
	JobID         int64 `json:"job_id"`
	TargetVersion int32 `json:"target_version"`
}

// Claim a batch of live, unleased entries by stamping claimed_at. SKIP LOCKED lets
// concurrent workers take disjoint rows; the lease predicate reclaims entries whose
// worker died (stale claimed_at), so no separate reaper process is needed.
func (q *Queries) ClaimEnrichmentBatch(ctx context.Context, arg ClaimEnrichmentBatchParams) ([]ClaimEnrichmentBatchRow, error) {
	rows, err := q.db.Query(ctx, claimEnrichmentBatch, arg.LeaseSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimEnrichmentBatchRow{}
	for rows.Next() {
		var i ClaimEnrichmentBatchRow
		if err := rows.Scan(&i.ID, &i.JobID, &i.TargetVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEnrichmentEntry = `-- name: DeleteEnrichmentEntry :exec
DELETE FROM enrichment_outbox
WHERE id = $1
`

func (q *Queries) DeleteEnrichmentEntry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteEnrichmentEntry, id)
	return err
}

const enqueuePendingJobs = `-- name: EnqueuePendingJobs :execrows
INSERT INTO enrichment_outbox (job_id, target_version)
SELECT id, $1::int
FROM jobs
WHERE enriched_at IS NULL OR enrichment_version < $1::int
ON CONFLICT (job_id, target_version) DO NOTHING
`

// Idempotent backfill: enqueue every job that is unenriched or below the target
// schema version. ON CONFLICT keeps exactly one entry per (job_id, target_version),
// so running this every command invocation never duplicates work.
func (q *Queries) EnqueuePendingJobs(ctx context.Context, targetVersion int32) (int64, error) {
	result, err := q.db.Exec(ctx, enqueuePendingJobs, targetVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordEnrichmentFailure = `-- name: RecordEnrichmentFailure :one
UPDATE enrichment_outbox
SET attempts   = attempts + 1,
    last_error = $1,
    failed_at  = CASE
                     WHEN attempts + 1 >= $2::int THEN now()
                     ELSE NULL
                 END
WHERE id = $3
RETURNING attempts, failed_at
`

type RecordEnrichmentFailureParams struct {
	LastError   string `json:"last_error"`
	MaxAttempts int32  `json:"max_attempts"`
	ID          int64  `json:"id"`
}

type RecordEnrichmentFailureRow struct {
	Attempts int32              `json:"attempts"`
	FailedAt pgtype.Timestamptz `json:"failed_at"`
}

// Count a failed attempt: bump attempts, record the error, and dead-letter (set
// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
// left in place — its expiry gates the retry to a later run and doubles as the
// crash reaper, so a failed entry is never reprocessed within the same run.
func (q *Queries) RecordEnrichmentFailure(ctx context.Context, arg RecordEnrichmentFailureParams) (RecordEnrichmentFailureRow, error) {
	row := q.db.QueryRow(ctx, recordEnrichmentFailure, arg.LastError, arg.MaxAttempts, arg.ID)
	var i RecordEnrichmentFailureRow
	err := row.Scan(&i.Attempts, &i.FailedAt)
	return i, err
}
