// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeUnseenJobs = `-- name: CloseUnseenJobs :execrows
UPDATE jobs
SET closed_at  = now(),
    updated_at = now()
WHERE closed_at IS NULL
  AND last_seen_at < $1
`

// Post-ingest sweep (see job-lifecycle spec): close every open job not seen since
// the cutoff. The caller owns the grace window (cutoff = now() - window) and the
// "run ingested something" guard, so a failed crawl never mass-closes the catalogue.
func (q *Queries) CloseUnseenJobs(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, closeUnseenJobs, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countJobs = `-- name: CountJobs :one
SELECT count(*)
FROM jobs
WHERE closed_at IS NULL
`

func (q *Queries) CountJobs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countJobs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueJobEnrichment = `-- name: EnqueueJobEnrichment :execrows
INSERT INTO enrichment_outbox (job_id, target_version)
SELECT id, $1::int
FROM jobs
WHERE id = $2::bigint
  AND (enriched_at IS NULL OR enrichment_version < $1::int)
ON CONFLICT (job_id, target_version) DO NOTHING
`

type EnqueueJobEnrichmentParams struct {
	TargetVersion int32 `json:"target_version"`
	JobID         int64 `json:"job_id"`
}

// Transactional-outbox enqueue for the ingest write path: queue this one job for
// enrichment, gated on the same condition the backfill uses (unenriched or below the
// target schema version), so an already-enriched job is not re-queued. Idempotent via
// the outbox's UNIQUE (job_id, target_version). Run in the same transaction as the
// job's UpsertJob so a newly ingested job is queued atomically with its write.
func (q *Queries) EnqueueJobEnrichment(ctx context.Context, arg EnqueueJobEnrichmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueJobEnrichment, arg.TargetVersion, arg.JobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getJob = `-- name: GetJob :one
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id int64) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
		&i.PublicSlug,
		&i.LastSeenAt,
		&i.ClosedAt,
	)
	return i, err
}

const getJobBySlug = `-- name: GetJobBySlug :one
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at
FROM jobs
WHERE public_slug = $1
`

func (q *Queries) GetJobBySlug(ctx context.Context, publicSlug string) (Job, error) {
	row := q.db.QueryRow(ctx, getJobBySlug, publicSlug)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
		&i.PublicSlug,
		&i.LastSeenAt,
		&i.ClosedAt,
	)
	return i, err
}

const getJobIDBySlug = `-- name: GetJobIDBySlug :one
SELECT id
FROM jobs
WHERE public_slug = $1
`

// Slim slug->id lookup for the view/apply interaction path, which needs only the
// internal id (the user_jobs FK) and must not drag the wide description/enrichment
// columns over the wire on every silent view. GetJobBySlug (SELECT *) stays for the
// public detail handler that renders the whole row.
func (q *Queries) GetJobIDBySlug(ctx context.Context, publicSlug string) (int64, error) {
	row := q.db.QueryRow(ctx, getJobIDBySlug, publicSlug)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at
FROM jobs
WHERE closed_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListJobsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Newest-added first: created_at is when the job entered the catalogue (stable
// across re-ingests), so fresh ingests surface on top regardless of how old the
// platform's posted_at is. id breaks ties within one ingest batch.
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
			&i.PublicSlug,
			&i.LastSeenAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByCompany = `-- name: ListJobsByCompany :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at
FROM jobs
WHERE company_slug = $1 AND closed_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2 OFFSET $3
`

type ListJobsByCompanyParams struct {
	CompanySlug string `json:"company_slug"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListJobsByCompany(ctx context.Context, arg ListJobsByCompanyParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByCompany, arg.CompanySlug, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
			&i.PublicSlug,
			&i.LastSeenAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByIDAfter = `-- name: ListJobsByIDAfter :many
SELECT id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at
FROM jobs
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListJobsByIDAfterParams struct {
	AfterID   int64 `json:"after_id"`
	BatchSize int32 `json:"batch_size"`
}

// Keyset scan for the reindex command: pages by the immutable primary key, so
// concurrent inserts/updates (which shift posted_at ordering) cannot make the
// scan skip or repeat rows the way OFFSET pagination would.
func (q *Queries) ListJobsByIDAfter(ctx context.Context, arg ListJobsByIDAfterParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByIDAfter, arg.AfterID, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.URL,
			&i.Title,
			&i.Company,
			&i.Location,
			&i.Remote,
			&i.Description,
			&i.PostedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.Enrichment,
			&i.EnrichedAt,
			&i.EnrichmentVersion,
			&i.PublicSlug,
			&i.LastSeenAt,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setJobEnrichment = `-- name: SetJobEnrichment :exec
UPDATE jobs
SET enrichment         = $1,
    enriched_at        = $2,
    enrichment_version = $3,
    updated_at         = now()
WHERE id = $4
`

type SetJobEnrichmentParams struct {
	Enrichment        json.RawMessage    `json:"enrichment"`
	EnrichedAt        pgtype.Timestamptz `json:"enriched_at"`
	EnrichmentVersion int32              `json:"enrichment_version"`
	ID                int64              `json:"id"`
}

// Targeted enrichment write used by the enrichment command: set only the payload
// and the provenance stamp, touching no raw source field. Kept separate from
// UpsertJob (the ingest full-upsert path) so ingest and enrichment stay decoupled.
func (q *Queries) SetJobEnrichment(ctx context.Context, arg SetJobEnrichmentParams) error {
	_, err := q.db.Exec(ctx, setJobEnrichment,
		arg.Enrichment,
		arg.EnrichedAt,
		arg.EnrichmentVersion,
		arg.ID,
	)
	return err
}

const updateJobSlugs = `-- name: UpdateJobSlugs :exec
UPDATE jobs
SET public_slug  = $1,
    company_slug = $2
WHERE id = $3
`

type UpdateJobSlugsParams struct {
	PublicSlug  string `json:"public_slug"`
	CompanySlug string `json:"company_slug"`
	ID          int64  `json:"id"`
}

// One-off backfill for a deliberate slug-builder change (see the UpsertJob note on
// why slugs are otherwise immutable). public_slug/company_slug are deterministic
// from the row's immutable fields, so recomputing and rewriting them is idempotent.
func (q *Queries) UpdateJobSlugs(ctx context.Context, arg UpdateJobSlugsParams) error {
	_, err := q.db.Exec(ctx, updateJobSlugs, arg.PublicSlug, arg.CompanySlug, arg.ID)
	return err
}

const upsertJob = `-- name: UpsertJob :one
WITH company_upsert AS (
    INSERT INTO companies (slug, name)
    SELECT $6, $5
    WHERE $6 <> ''
    ON CONFLICT (slug) DO UPDATE SET
        name       = EXCLUDED.name,
        updated_at = now()
)
INSERT INTO jobs (
    source, external_id, url, title, company, company_slug, location, remote, description, posted_at,
    public_slug
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    $11
)
ON CONFLICT (source, external_id) DO UPDATE SET
    url          = EXCLUDED.url,
    title        = EXCLUDED.title,
    company      = EXCLUDED.company,
    company_slug = EXCLUDED.company_slug,
    location     = EXCLUDED.location,
    remote       = EXCLUDED.remote,
    description  = EXCLUDED.description,
    posted_at    = EXCLUDED.posted_at,
    -- The crawl saw the posting: refresh liveness and reopen if it was closed.
    last_seen_at = now(),
    closed_at    = NULL,
    updated_at   = now()
RETURNING id, source, external_id, url, title, company, location, remote, description, posted_at, created_at, updated_at, company_slug, enrichment, enriched_at, enrichment_version, public_slug, last_seen_at, closed_at
`

type UpsertJobParams struct {
	Source      string             `json:"source"`
	ExternalID  string             `json:"external_id"`
	URL         string             `json:"url"`
	Title       string             `json:"title"`
	Company     string             `json:"company"`
	CompanySlug string             `json:"company_slug"`
	Location    string             `json:"location"`
	Remote      bool               `json:"remote"`
	Description string             `json:"description"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	PublicSlug  string             `json:"public_slug"`
}

// Single atomic write: upsert the company (only when the slug is non-empty,
// via the WHERE on the SELECT) and the job together, keeping the "one write =
// one job" property of the pipeline's write path.
// The enrichment columns are deliberately NOT written here: ingest carries no
// enrichment, so a new row takes the table defaults ('{}' / NULL / 0) and a
// re-ingest leaves any existing enrichment untouched. SetJobEnrichment (the
// enrichment worker) is the sole writer of those columns.
// public_slug is deliberately NOT in the DO UPDATE SET: the slug is minted once
// at insert and is the row's stable public identity. Re-ingest of the same
// (source, external_id) must not rewrite it, so external links stay valid even
// if the slug builder changes later (that would be a deliberate migration).
func (q *Queries) UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, upsertJob,
		arg.Source,
		arg.ExternalID,
		arg.URL,
		arg.Title,
		arg.Company,
		arg.CompanySlug,
		arg.Location,
		arg.Remote,
		arg.Description,
		arg.PostedAt,
		arg.PublicSlug,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.URL,
		&i.Title,
		&i.Company,
		&i.Location,
		&i.Remote,
		&i.Description,
		&i.PostedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanySlug,
		&i.Enrichment,
		&i.EnrichedAt,
		&i.EnrichmentVersion,
		&i.PublicSlug,
		&i.LastSeenAt,
		&i.ClosedAt,
	)
	return i, err
}
