// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type Company struct {
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EnrichmentOutbox struct {
	ID            int64              `json:"id"`
	JobID         int64              `json:"job_id"`
	TargetVersion int32              `json:"target_version"`
	Attempts      int32              `json:"attempts"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	LastError     string             `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID                int64              `json:"id"`
	Source            string             `json:"source"`
	ExternalID        string             `json:"external_id"`
	URL               string             `json:"url"`
	Title             string             `json:"title"`
	Company           string             `json:"company"`
	Location          string             `json:"location"`
	Remote            bool               `json:"remote"`
	Description       string             `json:"description"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompanySlug       string             `json:"company_slug"`
	Enrichment        json.RawMessage    `json:"enrichment"`
	EnrichedAt        pgtype.Timestamptz `json:"enriched_at"`
	EnrichmentVersion int32              `json:"enrichment_version"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
