// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID          int64              `json:"id"`
	UserID      int64              `json:"user_id"`
	Name        string             `json:"name"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type Company struct {
	Slug      string             `json:"slug"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type EnrichmentOutbox struct {
	ID            int64              `json:"id"`
	JobID         int64              `json:"job_id"`
	TargetVersion int32              `json:"target_version"`
	Attempts      int32              `json:"attempts"`
	ClaimedAt     pgtype.Timestamptz `json:"claimed_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	LastError     string             `json:"last_error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Job struct {
	ID                int64              `json:"id"`
	Source            string             `json:"source"`
	ExternalID        string             `json:"external_id"`
	URL               string             `json:"url"`
	Title             string             `json:"title"`
	Company           string             `json:"company"`
	Location          string             `json:"location"`
	Remote            bool               `json:"remote"`
	Description       string             `json:"description"`
	PostedAt          pgtype.Timestamptz `json:"posted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CompanySlug       string             `json:"company_slug"`
	Enrichment        json.RawMessage    `json:"enrichment"`
	EnrichedAt        pgtype.Timestamptz `json:"enriched_at"`
	EnrichmentVersion int32              `json:"enrichment_version"`
	PublicSlug        string             `json:"public_slug"`
	LastSeenAt        pgtype.Timestamptz `json:"last_seen_at"`
	ClosedAt          pgtype.Timestamptz `json:"closed_at"`
	Countries         []string           `json:"countries"`
	Regions           []string           `json:"regions"`
	WorkMode          string             `json:"work_mode"`
}

type TelegramPost struct {
	Channel     string             `json:"channel"`
	MsgID       int64              `json:"msg_id"`
	Text        string             `json:"text"`
	PostedAt    pgtype.Timestamptz `json:"posted_at"`
	FetchedAt   pgtype.Timestamptz `json:"fetched_at"`
	Attempts    int32              `json:"attempts"`
	ClaimedAt   pgtype.Timestamptz `json:"claimed_at"`
	FailedAt    pgtype.Timestamptz `json:"failed_at"`
	LastError   string             `json:"last_error"`
	ExtractedAt pgtype.Timestamptz `json:"extracted_at"`
	Links       []byte             `json:"links"`
}

type User struct {
	ID           int64              `json:"id"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserIdentity struct {
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	UserID         int64              `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type UserJob struct {
	UserID    int64              `json:"user_id"`
	JobID     int64              `json:"job_id"`
	ViewedAt  pgtype.Timestamptz `json:"viewed_at"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
	SavedAt   pgtype.Timestamptz `json:"saved_at"`
	Stage     pgtype.Text        `json:"stage"`
	Notes     pgtype.Text        `json:"notes"`
}
