// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Claim a batch of live, unleased entries by stamping claimed_at. SKIP LOCKED lets
	// concurrent workers take disjoint rows; the lease predicate reclaims entries whose
	// worker died (stale claimed_at), so no separate reaper process is needed.
	ClaimEnrichmentBatch(ctx context.Context, arg ClaimEnrichmentBatchParams) ([]ClaimEnrichmentBatchRow, error)
	// Claim a batch of pending posts by stamping claimed_at. SKIP LOCKED lets
	// concurrent workers take disjoint rows; the lease predicate reclaims posts whose
	// worker died (stale claimed_at), so no separate reaper process is needed.
	// Oldest post first so a backlog drains in posting order.
	ClaimTelegramPosts(ctx context.Context, arg ClaimTelegramPostsParams) ([]ClaimTelegramPostsRow, error)
	// Post-ingest sweep (see job-lifecycle spec): close every open job of ONE source not
	// seen since the cutoff. Scoped by source because ingest runs per provider — a
	// greenhouse run must not close jobs another provider owns and didn't crawl. The
	// caller owns the grace window (cutoff = now() - window) and the "run ingested
	// something" guard, so a failed crawl never mass-closes that source's catalogue.
	CloseUnseenJobs(ctx context.Context, arg CloseUnseenJobsParams) (int64, error)
	// Total companies matching the same optional name filter as ListCompanies, so
	// search pagination reports the filtered total.
	CountCompanies(ctx context.Context, search string) (int64, error)
	CountJobs(ctx context.Context) (int64, error)
	// Per-filter row counts for the my-jobs tabs, in one aggregate pass. "all" is
	// every interaction row; "viewed" is the view-only subset (neither saved nor
	// applied), matching the ListUserJobs filter.
	CountUserJobs(ctx context.Context, userID int64) (CountUserJobsRow, error)
	// Register a new account. email is stored as given (the handler lowercases it);
	// the unique index on lower(email) rejects duplicates regardless of case.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Link a provider identity to an account (first OAuth sign-in). The composite
	// primary key rejects a duplicate identity.
	CreateUserIdentity(ctx context.Context, arg CreateUserIdentityParams) error
	DeleteEnrichmentEntry(ctx context.Context, id int64) error
	// Drop companies no longer referenced by any job — the stale rows left behind
	// when a slug-builder change re-keys jobs onto new slugs.
	DeleteOrphanCompanies(ctx context.Context) (int64, error)
	// Transactional-outbox enqueue for the ingest write path: queue this one job for
	// enrichment, gated on the same condition the backfill uses (unenriched or below the
	// target schema version), so an already-enriched job is not re-queued. Idempotent via
	// the outbox's UNIQUE (job_id, target_version). Run in the same transaction as the
	// job's UpsertJob so a newly ingested job is queued atomically with its write.
	EnqueueJobEnrichment(ctx context.Context, arg EnqueueJobEnrichmentParams) (int64, error)
	// Idempotent backfill: enqueue every job that is unenriched or below the target
	// schema version. ON CONFLICT keeps exactly one entry per (job_id, target_version),
	// so running this every command invocation never duplicates work.
	EnqueuePendingJobs(ctx context.Context, targetVersion int32) (int64, error)
	GetCompany(ctx context.Context, slug string) (Company, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetJobBySlug(ctx context.Context, publicSlug string) (Job, error)
	// Slim slug->id lookup for the view/apply interaction path, which needs only the
	// internal id (the user_jobs FK) and must not drag the wide description/enrichment
	// columns over the wire on every silent view. GetJobBySlug (SELECT *) stays for the
	// public detail handler that renders the whole row.
	GetJobIDBySlug(ctx context.Context, publicSlug string) (int64, error)
	// Login lookup. Case-insensitive on email; returns password_hash so the handler
	// can verify the password (and reject accounts that have none).
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	// Profile lookup for the authenticated user. Never selects password_hash.
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	// OAuth sign-in fast path: resolve a provider identity straight to its user.
	GetUserByIdentity(ctx context.Context, arg GetUserByIdentityParams) (GetUserByIdentityRow, error)
	// Crawl write path: store a fetched post once. ON CONFLICT DO NOTHING makes
	// re-crawling idempotent — a stored post (pending, done, or dead-lettered) is
	// never reset. extracted_at is non-NULL when the ingest prefilter already
	// decided the post holds no vacancy, so it is recorded but never queued.
	InsertTelegramPost(ctx context.Context, arg InsertTelegramPostParams) (int64, error)
	// Catalog page: companies with their job counts. The job count is computed on
	// the fly (no denormalized counter yet). This is the one acknowledged place a
	// join to jobs is acceptable; LEFT JOIN keeps companies with zero jobs visible.
	// An empty `search` short-circuits the ILIKE, so the same prepared statement
	// serves both the full list and a name search (`search` is a case-insensitive
	// substring of the name).
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error)
	// Newest-added first: created_at is when the job entered the catalogue (stable
	// across re-ingests), so fresh ingests surface on top regardless of how old the
	// platform's posted_at is. id breaks ties within one ingest batch.
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListJobsByCompany(ctx context.Context, arg ListJobsByCompanyParams) ([]Job, error)
	// Keyset scan for the reindex command: pages by the immutable primary key, so
	// concurrent inserts/updates (which shift posted_at ordering) cannot make the
	// scan skip or repeat rows the way OFFSET pagination would.
	ListJobsByIDAfter(ctx context.Context, arg ListJobsByIDAfterParams) ([]Job, error)
	// A user's job interactions joined with the job rows, most recently touched
	// first (GREATEST ignores NULLs; viewed_at is always set). filter narrows to
	// viewed-only/saved/applied subsets; 'all' is every interaction, 'viewed' is
	// the passive history (rows neither saved nor applied). Closed jobs stay
	// listed: a user's history must not shrink when a posting closes.
	ListUserJobs(ctx context.Context, arg ListUserJobsParams) ([]ListUserJobsRow, error)
	// Mark a job as applied for a user. Idempotent and independent of a prior view:
	// it inserts the row (viewed_at defaults) or updates applied_at in place.
	MarkJobApplied(ctx context.Context, arg MarkJobAppliedParams) (UserJob, error)
	// Completion: the post was processed (jobs written, or no vacancy found). Run in
	// the same transaction as the extracted jobs' UpsertJob calls.
	MarkTelegramPostExtracted(ctx context.Context, arg MarkTelegramPostExtractedParams) error
	// Count a failed attempt: bump attempts, record the error, and dead-letter (set
	// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
	// left in place — its expiry gates the retry to a later run and doubles as the
	// crash reaper, so a failed entry is never reprocessed within the same run.
	RecordEnrichmentFailure(ctx context.Context, arg RecordEnrichmentFailureParams) (RecordEnrichmentFailureRow, error)
	// Record (or refresh) a user's view of a job. Idempotent on (user_id, job_id):
	// the first view creates the row, a repeat view touches viewed_at. Returns the
	// row so the caller learns the current applied_at in the same round-trip.
	RecordJobView(ctx context.Context, arg RecordJobViewParams) (UserJob, error)
	// Count a failed attempt: bump attempts, record the error, and dead-letter (set
	// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
	// left in place — its expiry gates the retry to a later run and doubles as the
	// crash reaper, so a failed post is never reprocessed within the same run.
	RecordTelegramPostFailure(ctx context.Context, arg RecordTelegramPostFailureParams) (RecordTelegramPostFailureRow, error)
	// Save (bookmark) a job for a user. Idempotent and independent of a prior view:
	// it inserts the row (viewed_at defaults) or refreshes saved_at in place.
	SaveJob(ctx context.Context, arg SaveJobParams) (UserJob, error)
	// Targeted enrichment write used by the enrichment command: set only the payload
	// and the provenance stamp, touching no raw source field. Kept separate from
	// UpsertJob (the ingest full-upsert path) so ingest and enrichment stay decoupled.
	SetJobEnrichment(ctx context.Context, arg SetJobEnrichmentParams) error
	// Rebuild the companies catalogue from jobs. The companies table is derivable
	// from jobs (slug = company_slug, name = company), so after a slug-builder change
	// re-keys jobs, this re-keys companies to match. DISTINCT ON collapses a slug's
	// name variants; ON CONFLICT folds collisions and refreshes existing rows.
	SyncCompaniesFromJobs(ctx context.Context) error
	// Clear a job's saved mark without deleting the interaction row, so view and
	// apply history survive unsaving. No interaction row -> pgx.ErrNoRows; the
	// handler treats that as "already not saved", never as a failure.
	UnsaveJob(ctx context.Context, arg UnsaveJobParams) (UserJob, error)
	// One-off backfill for a deliberate slug-builder change (see the UpsertJob note on
	// why slugs are otherwise immutable). public_slug/company_slug are deterministic
	// from the row's immutable fields, so recomputing and rewriting them is idempotent.
	UpdateJobSlugs(ctx context.Context, arg UpdateJobSlugsParams) error
	// Single atomic write: upsert the company (only when the slug is non-empty,
	// via the WHERE on the SELECT) and the job together, keeping the "one write =
	// one job" property of the pipeline's write path.
	// The enrichment columns are deliberately NOT written here: ingest carries no
	// enrichment, so a new row takes the table defaults ('{}' / NULL / 0) and a
	// re-ingest leaves any existing enrichment untouched. SetJobEnrichment (the
	// enrichment worker) is the sole writer of those columns.
	// public_slug is deliberately NOT in the DO UPDATE SET: the slug is minted once
	// at insert and is the row's stable public identity. Re-ingest of the same
	// (source, external_id) must not rewrite it, so external links stay valid even
	// if the slug builder changes later (that would be a deliberate migration).
	UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
