// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Claim a batch of live, unleased entries by stamping claimed_at. SKIP LOCKED lets
	// concurrent workers take disjoint rows; the lease predicate reclaims entries whose
	// worker died (stale claimed_at), so no separate reaper process is needed.
	ClaimEnrichmentBatch(ctx context.Context, arg ClaimEnrichmentBatchParams) ([]ClaimEnrichmentBatchRow, error)
	CountCompanies(ctx context.Context) (int64, error)
	CountJobs(ctx context.Context) (int64, error)
	// Register a new account. email is stored as given (the handler lowercases it);
	// the unique index on lower(email) rejects duplicates regardless of case.
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteEnrichmentEntry(ctx context.Context, id int64) error
	// Transactional-outbox enqueue for the ingest write path: queue this one job for
	// enrichment, gated on the same condition the backfill uses (unenriched or below the
	// target schema version), so an already-enriched job is not re-queued. Idempotent via
	// the outbox's UNIQUE (job_id, target_version). Run in the same transaction as the
	// job's UpsertJob so a newly ingested job is queued atomically with its write.
	EnqueueJobEnrichment(ctx context.Context, arg EnqueueJobEnrichmentParams) (int64, error)
	// Idempotent backfill: enqueue every job that is unenriched or below the target
	// schema version. ON CONFLICT keeps exactly one entry per (job_id, target_version),
	// so running this every command invocation never duplicates work.
	EnqueuePendingJobs(ctx context.Context, targetVersion int32) (int64, error)
	GetCompany(ctx context.Context, slug string) (Company, error)
	GetJob(ctx context.Context, id int64) (Job, error)
	GetJobBySlug(ctx context.Context, publicSlug string) (Job, error)
	// Login lookup. Case-insensitive on email; returns password_hash so the handler
	// can verify the password (and reject accounts that have none).
	GetUserByEmail(ctx context.Context, lower string) (User, error)
	// Profile lookup for the authenticated user. Never selects password_hash.
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	// Catalog page: companies with their job counts. The job count is computed on
	// the fly (no denormalized counter yet). This is the one acknowledged place a
	// join to jobs is acceptable; LEFT JOIN keeps companies with zero jobs visible.
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListJobsByCompany(ctx context.Context, arg ListJobsByCompanyParams) ([]Job, error)
	// Keyset scan for the reindex command: pages by the immutable primary key, so
	// concurrent inserts/updates (which shift posted_at ordering) cannot make the
	// scan skip or repeat rows the way OFFSET pagination would.
	ListJobsByIDAfter(ctx context.Context, arg ListJobsByIDAfterParams) ([]Job, error)
	// Mark a job as applied for a user. Idempotent and independent of a prior view:
	// it inserts the row (viewed_at defaults) or updates applied_at in place.
	MarkJobApplied(ctx context.Context, arg MarkJobAppliedParams) (UserJob, error)
	// Count a failed attempt: bump attempts, record the error, and dead-letter (set
	// failed_at) once attempts reach the max. The lease (claimed_at) is intentionally
	// left in place — its expiry gates the retry to a later run and doubles as the
	// crash reaper, so a failed entry is never reprocessed within the same run.
	RecordEnrichmentFailure(ctx context.Context, arg RecordEnrichmentFailureParams) (RecordEnrichmentFailureRow, error)
	// Record (or refresh) a user's view of a job. Idempotent on (user_id, job_id):
	// the first view creates the row, a repeat view touches viewed_at. Returns the
	// row so the caller learns the current applied_at in the same round-trip.
	RecordJobView(ctx context.Context, arg RecordJobViewParams) (UserJob, error)
	// Targeted enrichment write used by the enrichment command: set only the payload
	// and the provenance stamp, touching no raw source field. Kept separate from
	// UpsertJob (the ingest full-upsert path) so ingest and enrichment stay decoupled.
	SetJobEnrichment(ctx context.Context, arg SetJobEnrichmentParams) error
	// Single atomic write: upsert the company (only when the slug is non-empty,
	// via the WHERE on the SELECT) and the job together, keeping the "one write =
	// one job" property of the pipeline's write path.
	// The enrichment columns are deliberately NOT written here: ingest carries no
	// enrichment, so a new row takes the table defaults ('{}' / NULL / 0) and a
	// re-ingest leaves any existing enrichment untouched. SetJobEnrichment (the
	// enrichment worker) is the sole writer of those columns.
	// public_slug is deliberately NOT in the DO UPDATE SET: the slug is minted once
	// at insert and is the row's stable public identity. Re-ingest of the same
	// (source, external_id) must not rewrite it, so external links stay valid even
	// if the slug builder changes later (that would be a deliberate migration).
	UpsertJob(ctx context.Context, arg UpsertJobParams) (Job, error)
}

var _ Querier = (*Queries)(nil)
